#!/bin/bash
function Usage() {
	echo "Usage: scppi file_or_dir Username@piname:dest_file_or_dir"
	echo "Like This：scppi PiHealth pi@pi1:./new"
}
if [[ ! $# -eq 2 ]]; then
    Usage
    exit
fi

usrhoname=`echo $2|cut -d ":" -f 1|grep -w "^[a-zA-Z]@pi[0-9][0-9]"`

flag=file
if [[ -d ${} ]]; then
	flag=directory
fi
HostNum=`echo $Hostname | cut -c 3-`
port=$[6530 + $HostNum]
echo -e "\033[46;30m Coping $flag \033[46;31m$1\033[46;30m to \033[46;31m$dir_file\033[46;30m on \033[46;31m$Hostname\033[46;30m with Username \033[46;31m$Username\033[46;30m, enjoy it!\033[0m"
scp -P $port -r $1  ${Username}@localhost:$dir_file 





